### ISSUE TITLE
How to print my balance and get current exchange rate ETH to USD?

### ISSUE THREAD

**Issue by trungtien** [funyug/poloniex-api-client#1]
Hi,

I need to print my balance and get current exchange rate ETH to USD. Can you help me to do this?

**Comment by funyug** [comment]
To get your balance,you can use the **get_total_btc_balance()** function. To get ETH to USD rate, you can get the order book for ETH to USDT using **get_order_book("ETH_USDT")**

**Comment by trungtien** [comment]
Can you show the code?. I'm just beginner . 

```
<?php
$api = new Poloniex("myabc","myxyz");
$balance = $api->get_total_btc_balance(['BTC']);
echo $balance;

class Poloniex { 
...............................................
}
```
result:

PHP Fatal error:  Uncaught Exception: Curl error: Could not resolve host: poloniex.com in /home/tien/test.php:45
Stack trace:
#0 /home/tien/test.php(167): Poloniex->query(Array)
#1 /home/tien/test.php(3): Poloniex->get_total_btc_balance(Array)
#2 {main}
  thrown in /home/tien/test.php on line 45
![untitled](https://user-images.githubusercontent.com/16741935/27219923-87756618-52ad-11e7-8927-d5cd582e5bae.png)

**Comment by funyug** [comment]
Looks like your system is not able to connect to poloniex.com. Make sure you are connected to the internet and curl is working correctly on your system.

**Comment by trungtien** [comment]
Hi funyug,
This is my code.
![3](https://user-images.githubusercontent.com/16741935/27258018-62447840-5418-11e7-819b-683e7871a654.png)
and sure it was conenected to internet.
![1](https://user-images.githubusercontent.com/16741935/27258020-7c5398ce-5418-11e7-9d6c-1e0df6bab4f0.png)
Finally I got this error.
![untitled](https://user-images.githubusercontent.com/16741935/27258023-982e2f82-5418-11e7-8114-2ac3c5ba0948.png)

**Comment by funyug** [comment]
Can you paste your line 193 here?

**Comment by trungtien** [comment]
yep,
It's my line 193.
![untitled](https://user-images.githubusercontent.com/16741935/27258116-b4f7a15e-541b-11e7-9e2f-1c160502289d.png)
And this is similar of your code.
![untitled1](https://user-images.githubusercontent.com/16741935/27258119-c4fd099a-541b-11e7-9c6c-a3af2e13ab89.png)
I didn't change anything of your class. I just add some line . 
```
<?php
$api = new Poloniex("myabc","myxyz");
$balance = $api->get_total_btc_balance(['BTC']);
echo $balance;

class Poloniex { 
...............................................
}
```

**Comment by funyug** [comment]
it is strange, it is working for me. Can you add  print_r($balances) above the foreach statement and paste the output?

**Comment by trungtien** [comment]
It's same error:
"PHP Warning:  Invalid argument supplied for foreach() in /home/tien/poloniex-api-client/src/Poloniex.php on line 193"
Can you show me example code? change your api and secret key.

**Comment by funyug** [comment]
Your code is correct. Do you have any balance in your account?  I can fix this issue if you can print the output of $balances variable.

**Comment by trungtien** [comment]
Thanks a lot. Maybe I check something of mine. 
I really appriciated your help.
