### ISSUE TITLE
curl_init() curl_exec($ch) not working localy

### ISSUE THREAD

**Issue by ezerecero** [funyug/poloniex-api-client#3]
Hi! I have running the API working on a hosting and it works perfect, except like 2 weeks ago we had to modify this on the server because it was no retrieving data 

protected function retrieveJSON($URL) {
			$opts = array('http' =>
				array(
					'method'  => 'GET',
					'timeout' => 10 
				)
            ,
                **"ssl"=>array(
                    "verify_peer"=>false,
                    "verify_peer_name"=>false,
                )**
			);
			$context = stream_context_create($opts);
			$feed = file_get_contents($URL, false, $context);
			$json = json_decode($feed, true);
			return $json;
		}

But I have been trying to use the API localy with my Wondows 10 machine an my Mac Book Pro with high OS sierra and the response is not json with curl_exec, it retireves the same page. And I have noticed that when the $ch is created with the curl_init it takes the resource id='9' (I can see this with the debugger). A friend of mine has the same code woorking with a wondows 7 machine and the only diffreence is that, when the $ch is created he recieves the id='7' and works for him. 
Can you help me please!! I have tryed anything before asking to you gays and am sure you will have the answer. Thanks in advance.

**Comment by funyug** [comment]
Poloniex sometimes return cloudflare captcha page in response instead of json. You should try simple file_get_contents on the api and check the response.

**Comment by ezerecero** [comment]
I wonder how can thath be used with te API Key and Secret. Can you give me an axample how can I use for example $poloniex->get_balances(); with file_get_contents? Thanks in advance.
